on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v17
        with:
          name: kotfind
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix flake check --print-build-logs
